version: '3'

services:
  golang-app:
    image: go
    user: root
    privileged: true
    container_name: my-golang-app
    working_dir: /app
    ports:
      -  "9000:9000"
    volumes:
      - ../cfg.json:/cfg.json

volumes:
  data:
networks:
  default:
    # Use a custom driver
    driver: bridge